In [15]:
#intstalling libraries
#! pip install mysql-connector-python -- already satisfied
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3
#!pip install ipython-sql --  already installed

In [4]:
benefits = pd.read_csv('BenefitsCostSharing.csv')
benefits

C:\Users\chron\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3417: DtypeWarning: Columns (3,6,9,10,16,17,18) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,BenefitName,BusinessYear,CoinsInnTier1,CoinsInnTier2,CoinsOutofNet,CopayInnTier1,CopayInnTier2,CopayOutofNet,EHBVarReason,Exclusions,...,LimitUnit,MinimumStay,PlanId,QuantLimitOnSvc,RowNumber,SourceName,StandardComponentId,StateCode,StateCode2,VersionNum
0,Routine Dental Services (Adult),2014,20%,NaN,20%,No Charge,NaN,No Charge,Above EHB,NaN,...,Dollars per Year,NaN,21989AK0010001-00,Yes,68,HIOS,21989AK0010001,AK,AK,6
1,Dental Check-Up for Children,2014,20%,NaN,20%,No Charge,NaN,No Charge,Substantially Equal,NaN,...,Visit(s) per 6 Months,NaN,21989AK0010001-00,Yes,104,HIOS,21989AK0010001,AK,AK,6
2,Basic Dental Care - Child,2014,40%,NaN,40%,No Charge,NaN,No Charge,Substantially Equal,NaN,...,NaN,NaN,21989AK0010001-00,NaN,110,HIOS,21989AK0010001,AK,AK,6
3,Orthodontia - Child,2014,50%,NaN,50%,No Charge,NaN,No Charge,Additional EHB Benefit,NaN,...,NaN,NaN,21989AK0010001-00,NaN,111,HIOS,21989AK0010001,AK,AK,6
4,Major Dental Care - Child,2014,50%,NaN,50%,No Charge,NaN,No Charge,Substantially Equal,NaN,...,NaN,NaN,21989AK0010001-00,NaN,112,HIOS,21989AK0010001,AK,AK,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5048403,Major Dental Care - Child,2016,50% Coinsurance after deductible,NaN,50% Coinsurance after deductible,Not Applicable,NaN,Not Applicable,NaN,NaN,...,NaN,NaN,96480WV0110003-00,NaN,112,SERFF,96480WV0110003,WV,WV,2
5048404,Basic Dental Care - Adult,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,96480WV0110003-00,NaN,113,SERFF,96480WV0110003,WV,WV,2
5048405,Orthodontia - Adult,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,96480WV0110003-00,NaN,114,SERFF,96480WV0110003,WV,WV,2
5048406,Major Dental Care - Adult,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,96480WV0110003-00,NaN,115,SERFF,96480WV0110003,WV,WV,2
5048407,Accidental Dental,2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,96480WV0110003-00,NaN,118,SERFF,96480WV0110003,WV,WV,2

In [5]:
rules = pd.read_csv('BusinessRules.csv')
rules

,BusinessYear,StateCode,IssuerId,SourceName,VersionNum,ImportDate,IssuerId2,TIN,ProductId,StandardComponentId,...,DependentMaximumAgRule,ChildrenOnlyContractMaxChildrenRule,DomesticPartnerAsSpouseIndicator,SameSexPartnerAsSpouseIndicator,AgeDeterminationRule,MinimumTobaccoFreeMonthsRule,CohabitationRule,RowNumber,MarketCoverage,DentalOnlyPlan
0,2014,AL,82285,HIOS,7,2014-01-21 08:29:49,82285,94-2761537,NaN,82285AL0010006,...,26,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;War...",14,NaN,NaN
1,2014,AL,82285,HIOS,7,2014-01-21 08:29:49,82285,94-2761537,NaN,82285AL0020001,...,Not Applicable,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Adopted Child,Yes;Foster Child,Yes;Stepson or ...",15,NaN,NaN
2,2014,AL,82285,HIOS,7,2014-01-21 08:29:49,82285,94-2761537,NaN,82285AL0020002,...,Not Applicable,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Adopted Child,Yes;Foster Child,Yes;Stepson or ...",16,NaN,NaN
3,2014,AL,82285,HIOS,7,2014-01-21 08:29:49,82285,94-2761537,NaN,82285AL0020004,...,26,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;War...",17,NaN,NaN
4,2014,AL,82285,HIOS,7,2014-01-21 08:29:49,82285,94-2761537,NaN,82285AL0020006,...,26,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;War...",18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21080,2016,WV,94562,SERFF,2,2015-08-20 12:28:36,94562,13-5581829,94562WV008,94562WV0080001,...,21,3 or more,No,No,Age on effective date,Not Applicable,"Brother or Sister,Yes;Ward,Yes;Self,Yes;Child,...",10,SHOP (Small Group),Yes
21081,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,96480WV007,96480WV0070003,...,26,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;Ste...",11,SHOP (Small Group),Yes
21082,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,96480WV009,96480WV0090003,...,26,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;Ste...",12,SHOP (Small Group),Yes
21083,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,96480WV010,96480WV0100003,...,Not Applicable,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;Ste...",10,SHOP (Small Group),Yes
21084,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,96480WV011,96480WV0110003,...,Not Applicable,3 or more,Yes,Yes,Age on effective date,Not Applicable,"Spouse,No;Adopted Child,No;Foster Child,No;Ste...",10,SHOP (Small Group),Yes

In [6]:
crosswalk2015 = pd.read_csv('Crosswalk2015.csv')
crosswalk2015

C:\Users\chron\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3417: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,State,DentalPlan,PlanID_2014,IssuerID_2014,MultistatePlan_2014,MetalLevel_2014,ChildAdultOnly_2014,FIPSCode,ZipCode,CrosswalkLevel,...,PlanID_2015,IssuerID_2015,MultistatePlan_2015,MetalLevel_2015,ChildAdultOnly_2015,AgeOffPlanID_2015,IssuerID_AgeOff2015,MultistatePlan_AgeOff2015,MetalLevel_AgeOff2015,ChildAdultOnly_AgeOff2015
0,AK,Y,21989AK0010001,21989,N,Low,0,2013,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
1,AK,Y,21989AK0010001,21989,N,Low,0,2016,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
2,AK,Y,21989AK0010001,21989,N,Low,0,2020,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
3,AK,Y,21989AK0010001,21989,N,Low,0,2050,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
4,AK,Y,21989AK0010001,21989,N,Low,0,2060,0,1,...,21989AK0030001,21989,N,High,0,00000XX0000000,0,X,X,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132500,WY,Y,83964WY0010004,83964,N,High,0,56037,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132501,WY,Y,83964WY0010004,83964,N,High,0,56039,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132502,WY,Y,83964WY0010004,83964,N,High,0,56041,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132503,WY,Y,83964WY0010004,83964,N,High,0,56043,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X
132504,WY,Y,83964WY0010004,83964,N,High,0,56045,0,0,...,83964WY0010004,83964,N,High,0,00000XX0000000,0,X,X,X

In [7]:
crosswalk2016 = pd.read_csv('Crosswalk2016.csv')
crosswalk2016

,State,DentalPlan,PlanID_2015,IssuerID_2015,MultistatePlan_2015,MetalLevel_2015,ChildAdultOnly_2015,FIPSCode,ZipCode,CrosswalkLevel,...,PlanID_2016,IssuerID_2016,MultistatePlan_2016,MetalLevel_2016,ChildAdultOnly_2016,AgeOffPlanID_2016,IssuerID_AgeOff2016,MultistatePlan_AgeOff2016,MetalLevel_AgeOff2016,ChildAdultOnly_AgeOff2016
0,OR,N,10091OR0360004,10091,N,Bronze,0,41021,0,0,...,10091OR0360004,10091,N,Bronze,0,00000XX0000000,0,X,X,X
1,OR,N,10091OR0360004,10091,N,Bronze,0,41037,0,0,...,10091OR0360004,10091,N,Bronze,0,00000XX0000000,0,X,X,X
2,OR,N,10091OR0360004,10091,N,Bronze,0,41009,0,0,...,10091OR0360004,10091,N,Bronze,0,00000XX0000000,0,X,X,X
3,OR,N,10091OR0360004,10091,N,Bronze,0,41023,0,0,...,10091OR0360004,10091,N,Bronze,0,00000XX0000000,0,X,X,X
4,OR,N,10091OR0360004,10091,N,Bronze,0,41059,0,0,...,10091OR0360004,10091,N,Bronze,0,00000XX0000000,0,X,X,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150000,OH,Y,99969OH0060005,99969,N,High,0,39147,0,4,...,00000XX0000000,0,X,X,X,00000XX0000000,0,X,X,X
150001,OH,Y,99969OH0060005,99969,N,High,0,39035,0,4,...,00000XX0000000,0,X,X,X,00000XX0000000,0,X,X,X
150002,OH,Y,99969OH0060005,99969,N,High,0,39003,0,4,...,00000XX0000000,0,X,X,X,00000XX0000000,0,X,X,X
150003,OH,Y,99969OH0060005,99969,N,High,0,39083,0,4,...,00000XX0000000,0,X,X,X,00000XX0000000,0,X,X,X
150004,OH,Y,99969OH0060005,99969,N,High,0,39019,0,4,...,00000XX0000000,0,X,X,X,00000XX0000000,0,X,X,X

In [8]:
network = pd.read_csv('Network.csv')
network

,BusinessYear,StateCode,IssuerId,SourceName,VersionNum,ImportDate,IssuerId2,StateCode2,NetworkName,NetworkId,NetworkURL,RowNumber,MarketCoverage,DentalOnlyPlan
0,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,AK,ODS Premier,AKN001,https://www.modahealth.com/ProviderSearch/face...,13,NaN,NaN
1,2014,AK,38344,HIOS,6,2013-08-28 08:15:53,38344,AK,HeritagePlus,AKN001,https://www.premera.com/wa/visitor/,13,NaN,NaN
2,2014,AK,38536,HIOS,2,2013-08-01 12:48:00,38536,AK,Lincoln Dental Connect,AKN001,http://lfg.go2dental.com/member/dental_search/...,13,NaN,NaN
3,2014,AK,42507,HIOS,3,2013-09-02 11:39:25,42507,AK,DentalGuard Preferred,AKN001,https://www.guardiananytime.com/fpapp/FPWeb/de...,13,NaN,NaN
4,2014,AK,73836,HIOS,6,2014-04-18 11:49:29,73836,AK,Moda Plus AK Regional,AKN001,https://www.modahealth.com/ProviderSearch/face...,13,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3817,2016,WV,75441,SERFF,2,2015-08-20 12:28:36,75441,WV,"DenteMax, LLC",WVN001,www.dentemax.com,13,SHOP (Small Group),Yes
3818,2016,WV,76526,SERFF,4,2015-08-20 12:28:36,76526,WV,Delta Dental PPO,WVN001,https://www.deltadentalins.com/find-a-dentist,13,SHOP (Small Group),Yes
3819,2016,WV,76526,SERFF,4,2015-08-20 12:28:36,76526,WV,Delta Dental PPO,WVN001,https://www.deltadentalins.com/find-a-dentist,13,Individual,Yes
3820,2016,WV,94562,SERFF,2,2015-08-20 12:28:36,94562,WV,PDP PLUS,WVN001,https://metlocator.metlife.com/metlocator/exec...,13,SHOP (Small Group),Yes
3821,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,WV,DentalGuard Preferred,WVN001,https://www.guardiananytime.com/fpapp/FPWeb/de...,13,SHOP (Small Group),Yes

In [9]:
planattributes = pd.read_csv('PlanAttributes.csv')
planattributes

C:\Users\chron\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3417: DtypeWarning: Columns (0,7,8,9,10,11,12,13,14,15,18,19,20,22,23,24,25,26,27,28,29,31,32,33,34,39,40,41,42,66,67,68,70,71,72,75,76,77,79,80,81,82,84,85,86,88,89,90,92,93,94,96,97,98,136,137,138,140,141,142,145,146,147,150,151,152,154,155,156,158,159,160,162,163,164,166,167,168) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,AVCalculatorOutputNumber,BeginPrimaryCareCostSharingAfterNumberOfVisits,BeginPrimaryCareDeductibleCoinsuranceAfterNumberOfCopays,BenefitPackageId,BusinessYear,CSRVariationType,ChildOnlyOffering,ChildOnlyPlanId,CompositeRatingOffered,DEHBCombInnOonFamilyMOOP,...,TEHBOutOfNetFamilyMOOP,TEHBOutOfNetFamilyPerGroupMOOP,TEHBOutOfNetFamilyPerPersonMOOP,TEHBOutOfNetIndividualMOOP,TIN,URLForEnrollmentPayment,URLForSummaryofBenefitsCoverage,UniquePlanDesign,VersionNum,WellnessProgramOffered
0,NaN,0,0,1,2014,Standard Low Off Exchange Plan,Allows Adult and Child-Only,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,93-0438772,https://www.modahealth.com/employers/enroll.shtml,https://www.modahealth.com/producers/grp/den.s...,NaN,6,NaN
1,NaN,0,0,1,2014,Standard Low On Exchange Plan,Allows Adult and Child-Only,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,93-0438772,https://www.modahealth.com/employers/enroll.shtml,https://www.modahealth.com/producers/grp/den.s...,NaN,6,NaN
2,NaN,0,0,1,2014,Standard High Off Exchange Plan,Allows Adult and Child-Only,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,93-0438772,https://www.modahealth.com/employers/enroll.shtml,https://www.modahealth.com/producers/grp/den.s...,NaN,6,NaN
3,NaN,0,0,1,2014,Standard Low Off Exchange Plan,Allows Adult and Child-Only,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,93-0438772,https://www.modahealth.com/mymoda/,https://www.modahealth.com/pdfs/plans/individu...,NaN,6,NaN
4,NaN,0,0,1,2014,Standard Low On Exchange Plan,Allows Adult and Child-Only,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,93-0438772,https://www.modahealth.com/mymoda/,https://www.modahealth.com/pdfs/plans/individu...,NaN,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77348,NaN,0,0,1,2016,Standard Low Off Exchange Plan,Allows Child-Only,NaN,No,NaN,...,NaN,NaN,NaN,NaN,13-5123390,NaN,https://www.guardiananytime.com/dental-health-...,NaN,2,NaN
77349,NaN,0,0,2,2016,Standard High Off Exchange Plan,Allows Adult and Child-Only,NaN,No,NaN,...,NaN,NaN,NaN,NaN,13-5123390,NaN,https://www.guardiananytime.com/dental-health-...,NaN,2,NaN
77350,NaN,0,0,2,2016,Standard High On Exchange Plan,Allows Adult and Child-Only,NaN,No,NaN,...,NaN,NaN,NaN,NaN,13-5123390,NaN,https://www.guardiananytime.com/dental-health-...,NaN,2,NaN
77351,NaN,0,0,2,2016,Standard Low Off Exchange Plan,Allows Adult and Child-Only,NaN,No,NaN,...,NaN,NaN,NaN,NaN,13-5123390,NaN,https://www.guardiananytime.com/dental-health-...,NaN,2,NaN
77352,NaN,0,0,2,2016,Standard Low On Exchange Plan,Allows Adult and Child-Only,NaN,No,NaN,...,NaN,NaN,NaN,NaN,13-5123390,NaN,https://www.guardiananytime.com/dental-health-...,NaN,2,NaN

In [10]:
rates = pd.read_csv('Rate.csv')
rates

,BusinessYear,StateCode,IssuerId,SourceName,VersionNum,ImportDate,IssuerId2,FederalTIN,RateEffectiveDate,RateExpirationDate,...,IndividualRate,IndividualTobaccoRate,Couple,PrimarySubscriberAndOneDependent,PrimarySubscriberAndTwoDependents,PrimarySubscriberAndThreeOrMoreDependents,CoupleAndOneDependent,CoupleAndTwoDependents,CoupleAndThreeOrMoreDependents,RowNumber
0,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,29.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
1,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,36.95,NaN,73.9,107.61,107.61,107.61,144.56,144.56,144.56,14
2,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,36.95,NaN,73.9,107.61,107.61,107.61,144.56,144.56,144.56,15
3,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
4,2014,AK,21989,HIOS,6,2014-03-19 07:06:49,21989,93-0438772,2014-01-01,2014-12-31,...,32.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12694440,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2033
12694441,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2034
12694442,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2035
12694443,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2036
12694444,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,13-5123390,2016-01-01,2016-12-31,...,14.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2037

In [11]:
servicearea = pd.read_csv('ServiceArea.csv')
servicearea

,BusinessYear,StateCode,IssuerId,SourceName,VersionNum,ImportDate,IssuerId2,StateCode2,ServiceAreaId,ServiceAreaName,CoverEntireState,County,PartialCounty,ZipCodes,PartialCountyJustification,RowNumber,MarketCoverage,DentalOnlyPlan
0,2014,PA,22444,HIOS,9,2014-01-21 08:29:49,22444,PA,PAS001,Geisinger Health Plan,No,42103.0,No,NaN,NaN,42,NaN,NaN
1,2014,PA,22444,HIOS,9,2014-01-21 08:29:49,22444,PA,PAS001,Geisinger Health Plan,No,42105.0,No,NaN,NaN,43,NaN,NaN
2,2014,PA,22444,HIOS,9,2014-01-21 08:29:49,22444,PA,PAS001,Geisinger Health Plan,No,42107.0,No,NaN,NaN,44,NaN,NaN
3,2014,PA,22444,HIOS,9,2014-01-21 08:29:49,22444,PA,PAS001,Geisinger Health Plan,No,42109.0,No,NaN,NaN,45,NaN,NaN
4,2014,PA,22444,HIOS,9,2014-01-21 08:29:49,22444,PA,PAS001,Geisinger Health Plan,No,42111.0,No,NaN,NaN,46,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42242,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,WV,WVS001,"DentalGuard Preferred Group & Individual PPO, ...",No,54095.0,No,NaN,NaN,27,SHOP (Small Group),Yes
42243,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,WV,WVS001,"DentalGuard Preferred Group & Individual PPO, ...",No,54101.0,No,NaN,NaN,28,SHOP (Small Group),Yes
42244,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,WV,WVS001,"DentalGuard Preferred Group & Individual PPO, ...",No,54103.0,No,NaN,NaN,29,SHOP (Small Group),Yes
42245,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,WV,WVS001,"DentalGuard Preferred Group & Individual PPO, ...",No,54105.0,No,NaN,NaN,30,SHOP (Small Group),Yes
42246,2016,WV,96480,SERFF,2,2015-08-20 12:28:36,96480,WV,WVS001,"DentalGuard Preferred Group & Individual PPO, ...",No,54107.0,No,NaN,NaN,31,SHOP (Small Group),Yes